---
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: phpmyadmin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

