---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: phpmyadmin
  annotations:
    argocd.argoproj.io/sync-wave: "0"
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: wordpress
