---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: database
spec:
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
